# Generated by Django 4.1.3 on 2023-01-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to=None)),
                ('category', models.CharField(choices=[('Textile', 'Textile'), ('Furniture', 'Furniture'), ('Leather', 'Leather')], max_length=10)),
            ],
        ),
    ]
